-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer
    -   id: mixed-line-ending
    -   id: end-of-file-fixer
    -   id: detect-private-key
    -   id: check-docstring-first
    -   id: check-case-conflict
    -   id: check-ast

